"""Generates the committed squat replay corpus (Stage 5.7, respecced under the real
model in Stage 5.8 — see point 2 below).

Synthetic side-view squat sets spanning every band the shipped model has been found to
actually reach (Good and Fair — **not Poor**; see point 2), plus a low-capture-quality
reject, committed to `backend/app/module_b/replay_corpus/squat/` so the determinism
tests and the replay harness run from fixed data without needing the REHAB24-6 dataset
(which lives outside the repo and cannot be committed).

Mirrors Module A's Stage 7 precedent (`generate_sls_replay_corpus.py`): fixed seed,
committed output, a `labels.json` manifest. Three things differ, each for a reason.

1. **The manifest records what each sample *actually* produced, not what it was
   designed to produce.** Module A's corpus stores a `target_band_hint`. Here every
   sample is run through the real pipeline at build time and the *measured* band, rule
   score and flags are written to `labels.json`. The intended band is kept alongside as
   `target_band_hint`, and `hint_matched` records whether they agree. A hand-written
   expectation that silently stops matching the code is exactly the kind of stale
   fixture this corpus exists to catch.

2. **Which band a sample reaches now depends on a trained, non-analytic model
   (Stage 5.8), and this corpus no longer includes a Poor sample — because none could
   be found, and that absence is itself a documented finding, not an oversight.**
   Before Stage 5.8, the Phase 4 `StubModel` placeholder derived
   `P(Good) = rule_score/10` exactly, so a sample's band could be predicted from its
   `rule_score` by a simple formula, and "deep + unstable" reliably read as Poor
   (rewarding depth is what the analytic rule score does). `get_model_bundle("squat")`
   replaced it with the real Extra Trees forest + sigmoid calibration, which learned
   the **opposite** relationship for this population — Stage 5.4/5.5/5.6 already
   established that incorrect repetitions in this dataset are *deeper*, not shallower —
   so the old "deep + unstable = Poor" specs now read as confidently *Good* or merely
   uncertain instead.

   Rebuilding the specs around the real model's actual (measured, not assumed) Good/Poor
   feature statistics and then sweeping depth, lean, tempo and sway against
   `get_model_bundle("squat")` directly, the lowest confidence toward Poor reached by
   any geometry tried — including implausibly extreme ones — was P(Good)≈0.50, well
   short of the ≤0.15 that `confidence_low_threshold=0.85` requires to band Poor. This
   matches a stronger, independently-measured fact: `export_squat_model.py`'s own
   `_deployed_confidence_check()` found that **the single most Poor-leaning row in the
   entire 98-repetition training set** only reaches P(Good)=0.244 — the shipped
   model never crosses the confidence bar toward Poor on its own training data, let
   alone on synthetic geometry it has never seen. Two closest-approach samples
   (`attempted_poor_deep_unstable_1`/`_2`) are kept to record this rather than silently
   dropped; their `target_band_hint` is honestly `"Fair"`.

   The corpus remains a **determinism fixture, not a correctness oracle** — it is not
   evidence the model is accurate on synthetic geometry, only that it is deterministic
   on it. `labels.json`'s `measured` block is regenerated by re-running this script,
   never hand-patched, exactly because no formula can predict it.

3. **Geometry is built from joint angles, forwards.** Rather than hand-placing
   landmarks and hoping the resulting angles land somewhere useful, each frame is
   constructed from a target knee flexion and shank tilt, so a spec says what it means.
   The build then verifies the constructed pose reproduces the requested angle through
   the *real* `mean_knee_flexion_deg()` (X1) rather than trusting the construction.

Deterministic (X8): seeded RNG, fixed specs, sorted iteration, no wall-clock.

Usage:
    python generate_squat_replay_corpus.py
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path

from app.module_b.core.config import MODULE_B_CORE_CONFIG
from app.module_b.core.fusion import fuse_model
from app.module_b.core.model_registry import get_model_bundle
from app.module_b.core.preprocessing import preprocess_world_landmarks
from app.module_b.core.quality import assess_capture_quality
from app.module_b.squat.features import extract_squat_features
from app.module_b.squat.rules import score_squat_set
from app.module_b.squat.segmentation import mean_knee_flexion_deg, segment_squat_frames

CORPUS_DIR = (
    Path(__file__).resolve().parents[2]
    / "backend"
    / "app"
    / "module_b"
    / "replay_corpus"
    / "squat"
)

SEED = 20260716
FPS = 30.0  # REHAB24-6's rate, and a realistic webcam rate
FRAME_DT = 1.0 / FPS
STANDING_FLEXION_DEG = 5.0
STANDING_PAD_S = 0.6  # standing frames either side, so the FSM starts/ends in READY

# Segment lengths in metres, roughly adult proportions. Only their ratios matter.
SHANK_LEN = 0.42
THIGH_LEN = 0.42
TRUNK_LEN = 0.50
HALF_STANCE_Z = 0.09  # ankles at z = +-0.09 -> stance width 0.18 m

# Jitter noise is tiny and only exists so frames are not bit-identical; the
# *intended* instability in a spec comes from `sway_amplitude`, not from this.
POSE_NOISE_M = 0.001


def _r(value: float) -> float:
    """4dp is well beyond what these synthetic coordinates need; rounding keeps the
    committed JSON compact (default float repr bloats the file)."""
    return round(value, 4)


def _leg_points(
    flexion_deg: float, shank_tilt_deg: float, ankle_y: float
) -> tuple[tuple[float, float], tuple[float, float], tuple[float, float]]:
    """Build (ankle, knee, hip) in the sagittal x-y plane from joint angles.

    x is forward, y is *down* (MediaPipe world convention). The knee's interior angle
    is set to `180 - flexion_deg`, so `knee_flexion_deg()` reads back `flexion_deg`.
    Of the two possible hip placements, the higher one (smaller y) is the anatomical
    one — a squat bends the knee with the hip above it, not below.
    """
    ankle = (0.0, ankle_y)
    tilt = math.radians(shank_tilt_deg)
    knee = (
        ankle[0] + SHANK_LEN * math.sin(tilt),
        ankle[1] - SHANK_LEN * math.cos(tilt),
    )

    # Direction knee -> ankle, and the two candidate thigh directions at the required
    # interior angle from it.
    to_ankle = math.atan2(ankle[1] - knee[1], ankle[0] - knee[0])
    interior = math.radians(180.0 - flexion_deg)
    candidates = [
        (
            knee[0] + THIGH_LEN * math.cos(to_ankle + interior),
            knee[1] + THIGH_LEN * math.sin(to_ankle + interior),
        ),
        (
            knee[0] + THIGH_LEN * math.cos(to_ankle - interior),
            knee[1] + THIGH_LEN * math.sin(to_ankle - interior),
        ),
    ]
    hip = min(candidates, key=lambda point: point[1])
    return ankle, knee, hip


def _make_world(
    flexion_deg: float,
    shank_tilt_deg: float,
    trunk_lean_deg: float,
    sway_x: float,
    visibility: float,
    rng: random.Random,
) -> list[dict]:
    """One 33-landmark world pose. Only the indices Module B reads are meaningful.

    `sway_x` translates the whole body, so it perturbs `hip_mid_jitter_norm` (which
    measures hip travel) without touching any joint angle *in the raw pose*.

    It does not stay independent downstream, and that is worth knowing rather than
    assuming: One Euro's cutoff is speed-adaptive (`min_cutoff + beta * |velocity|`), so
    a large sway raises the x-velocity, widens the cutoff, and therefore smooths the
    landmark *less*. Measured on this corpus: raw peak knee flexion is identical
    (36.19 deg) at sway 0.0 and 0.4, but the preprocessed peak moves 35.44 -> 36.44 deg,
    which is enough to change how many reps segment. Whole-body translation is coupled
    to angle smoothing through the filter, not through the geometry.
    """
    ankle, knee, hip = _leg_points(flexion_deg, shank_tilt_deg, ankle_y=1.0)
    lean = math.radians(trunk_lean_deg)
    shoulder = (
        hip[0] + TRUNK_LEN * math.sin(lean),
        hip[1] - TRUNK_LEN * math.cos(lean),
    )

    def point(xy: tuple[float, float], z: float) -> dict:
        return {
            "x": _r(xy[0] + sway_x + rng.uniform(-POSE_NOISE_M, POSE_NOISE_M)),
            "y": _r(xy[1] + rng.uniform(-POSE_NOISE_M, POSE_NOISE_M)),
            "z": _r(z),
            "visibility": visibility,
        }

    zero = {"x": 0.0, "y": 0.0, "z": 0.0, "visibility": visibility}
    world = [dict(zero) for _ in range(33)]
    # Left/right are identical apart from their z offset: a true sagittal view cannot
    # distinguish them anyway (see the symmetry_index limitation in the reports), so
    # inventing an asymmetry here would fake a signal the geometry does not carry.
    for index, xy in ((11, shoulder), (23, hip), (25, knee), (27, ankle)):
        world[index] = point(xy, -HALF_STANCE_Z)
    for index, xy in ((12, shoulder), (24, hip), (26, knee), (28, ankle)):
        world[index] = point(xy, HALF_STANCE_Z)
    return world


def _flexion_profile(peak_deg: float, duration_s: float) -> list[float]:
    """One rep's knee-flexion trajectory: a raised cosine from standing to `peak_deg`.

    Smooth by construction, so the segmentation FSM sees a clean single-peak descent
    and ascent rather than threshold chatter — the corpus tests replay determinism, so
    a sample that segments ambiguously would be testing the wrong thing.
    """
    n_frames = max(int(round(duration_s * FPS)), 2)
    return [
        STANDING_FLEXION_DEG
        + (peak_deg - STANDING_FLEXION_DEG)
        * 0.5
        * (1.0 - math.cos(2.0 * math.pi * i / n_frames))
        for i in range(n_frames)
    ]


def _build_frames(spec: dict, rng: random.Random) -> list[dict]:
    """Assemble a whole set: standing pad, `n_reps` reps, standing pad."""
    flexions: list[float] = []
    pad = [STANDING_FLEXION_DEG] * int(round(STANDING_PAD_S * FPS))
    flexions.extend(pad)
    for rep_index in range(spec["n_reps"]):
        # Per-rep duration jitter drives tempo_consistency; a spec asking for an
        # inconsistent tempo gets genuinely uneven reps, not a hand-set feature value.
        duration = spec["rep_duration_s"] * (
            1.0 + spec["duration_variation"] * (rep_index - (spec["n_reps"] - 1) / 2.0)
        )
        flexions.extend(_flexion_profile(spec["peak_flexion_deg"], duration))
        flexions.extend([STANDING_FLEXION_DEG] * int(round(0.4 * FPS)))
    flexions.extend(pad)

    frames = []
    for i, flexion in enumerate(flexions):
        t = i * FRAME_DT
        progress = (flexion - STANDING_FLEXION_DEG) / max(
            spec["peak_flexion_deg"] - STANDING_FLEXION_DEG, 1e-9
        )
        # Shank tilt and trunk lean both grow with depth, as they do in a real squat.
        shank_tilt = spec["shank_tilt_deg"] * progress
        trunk_lean = spec["trunk_lean_deg"] * progress
        sway_x = spec["sway_amplitude"] * math.sin(2.0 * math.pi * spec["sway_hz"] * t)
        frames.append(
            {
                "timestampMs": round(t * 1000.0, 1),
                "worldLandmarks": _make_world(
                    flexion, shank_tilt, trunk_lean, sway_x, spec["visibility"], rng
                ),
            }
        )
    return frames


# Specs are tuned so each lands in its intended band, but the manifest records the
# MEASURED band regardless -- see the module docstring, point 1. `visibility` below
# 0.6 (MIN_VISIBILITY) is what makes the low-Q sample a reject.
#
# These specs were substantially rebuilt after Stage 5.8 swapped in the real trained
# model (module docstring, point 2). The ORIGINAL specs were tuned against the
# ANALYTIC rule score, which rewards depth; the real forest learned the OPPOSITE
# relationship for this population (incorrect reps are deeper — Stage 5.4/5.5/5.6's
# own finding), so "deep + unstable" specs that used to read as confidently Poor under
# StubModel now read as confidently GOOD or merely uncertain under the real model.
# Every spec below was re-derived by sweeping geometry against the real
# `get_model_bundle("squat")` and reading off what it actually predicts — not assumed
# to transfer from the old, StubModel-era intent.
SAMPLE_SPECS = [
    {
        "sample_id": "good_moderate_depth_1",
        "peak_flexion_deg": 75.0,
        "n_reps": 3,
        "rep_duration_s": 3.0,
        "duration_variation": 0.0,
        "shank_tilt_deg": 28.0,
        "trunk_lean_deg": 25.0,
        "sway_amplitude": 0.0,
        "sway_hz": 0.0,
        "visibility": 0.98,
        "target_band_hint": "Good",
    },
    {
        "sample_id": "good_moderate_depth_2",
        "peak_flexion_deg": 95.0,
        "n_reps": 3,
        "rep_duration_s": 3.4,
        "duration_variation": 0.0,
        "shank_tilt_deg": 28.0,
        "trunk_lean_deg": 25.0,
        "sway_amplitude": 0.0,
        "sway_hz": 0.0,
        "visibility": 0.95,
        "target_band_hint": "Good",
    },
    {
        # Uncertain from the Good side: real forest P(Good) ~0.81, just below the
        # 0.85 confidence bar -> routed to Fair via low_confidence, not via the score
        # band. Deeper/more-lean than the Good samples above but not extreme.
        "sample_id": "fair_uncertain_good_leaning_1",
        "peak_flexion_deg": 120.0,
        "n_reps": 3,
        "rep_duration_s": 3.0,
        "duration_variation": 0.0,
        "shank_tilt_deg": 28.0,
        "trunk_lean_deg": 35.0,
        "sway_amplitude": 0.0,
        "sway_hz": 0.0,
        "visibility": 0.92,
        "target_band_hint": "Fair",
    },
    {
        # Uncertain from further along the same direction: P(Good) ~0.68, closer to
        # the 0.5 midpoint than the sample above.
        "sample_id": "fair_uncertain_poor_leaning_1",
        "peak_flexion_deg": 125.0,
        "n_reps": 3,
        "rep_duration_s": 3.0,
        "duration_variation": 0.0,
        "shank_tilt_deg": 28.0,
        "trunk_lean_deg": 45.0,
        "sway_amplitude": 0.0,
        "sway_hz": 0.0,
        "visibility": 0.90,
        "target_band_hint": "Fair",
    },
    # The two samples below deliberately probe the SAME question Stage 5.8's export
    # script asks of the model itself (see export_squat_model.py's
    # _deployed_confidence_check): can ANY input make the shipped model confidently
    # predict Poor? A sweep over depth/lean/tempo/sway found the answer is no for
    # every geometry tried, including implausibly extreme ones -- the lowest P(Good)
    # reached was ~0.50, still short of the <=0.15 needed for confidence>=0.85 toward
    # Poor. That matches a harder fact measured directly at export time: even the
    # single MOST Poor-leaning row in the entire 98-repetition training set only
    # reaches P(Good)=0.244. These two samples are kept as the closest approach found,
    # not as a working "Poor" fixture -- their `target_band_hint` is honestly "Fair",
    # and `hint_matched` records that this is expected, not a bug.
    {
        "sample_id": "attempted_poor_deep_unstable_1",
        "peak_flexion_deg": 150.0,
        "n_reps": 3,
        "rep_duration_s": 0.9,
        "duration_variation": 0.0,
        "shank_tilt_deg": 50.0,
        "trunk_lean_deg": 55.0,
        "sway_amplitude": 0.15,
        "sway_hz": 3.0,
        "visibility": 0.88,
        "target_band_hint": "Fair",
    },
    {
        "sample_id": "attempted_poor_deep_unstable_2",
        "peak_flexion_deg": 150.0,
        "n_reps": 4,
        "rep_duration_s": 0.8,
        "duration_variation": 0.15,
        "shank_tilt_deg": 45.0,
        "trunk_lean_deg": 70.0,
        "sway_amplitude": 0.10,
        "sway_hz": 3.0,
        "visibility": 0.86,
        "target_band_hint": "Fair",
    },
    {
        # Geometry identical to a Good sample; only visibility is degraded, so this
        # isolates the capture-quality gate from the movement itself. Robust to the
        # StubModel->real-model swap by construction: low_capture_quality forces Fair
        # before the model's prediction is ever consulted.
        "sample_id": "lowq_reject_occluded_1",
        "peak_flexion_deg": 75.0,
        "n_reps": 3,
        "rep_duration_s": 3.0,
        "duration_variation": 0.0,
        "shank_tilt_deg": 28.0,
        "trunk_lean_deg": 25.0,
        "sway_amplitude": 0.0,
        "sway_hz": 0.0,
        "visibility": 0.45,
        "target_band_hint": "Fair",
    },
]


def analyse(frames: list[dict]) -> dict:
    """Run the real router pipeline over one sample's frames (X1).

    Deliberately mirrors `router.py`'s exact order and semantics — quality on the raw
    buffer, preprocessing over the whole stream, then segment/extract/score/fuse —
    rather than re-deriving a convenient variant. This is what makes the measured band
    in `labels.json` the band the live endpoint would actually return.
    """
    quality = assess_capture_quality(frames)
    preprocessed = preprocess_world_landmarks(frames)
    reps = segment_squat_frames(preprocessed)
    if not reps:
        return {"n_reps": 0, "band": None, "error": "no reps segmented"}

    feature_vectors = [extract_squat_features(rep) for rep in reps]
    rule_scores = score_squat_set(reps and feature_vectors)
    if rule_scores.score is None:
        return {"n_reps": len(reps), "band": None, "error": "no rule score"}

    fusion = fuse_model(
        rule_scores=rule_scores,
        model=get_model_bundle("squat"),
        features=feature_vectors[0],
        q=float(quality["q"]),
    )
    return {
        "n_reps": len(reps),
        "band": fusion.band,
        "score": round(fusion.score, 4),
        "rule_score": round(rule_scores.score, 4),
        "confidence": round(fusion.confidence, 4),
        "q": round(float(quality["q"]), 4),
        "flags": list(fusion.flags),
        "peak_knee_flexion_deg": round(
            max(mean_knee_flexion_deg(f) for f in preprocessed), 2
        ),
    }


def _verify_construction(spec: dict, frames: list[dict]) -> None:
    """Check the built pose actually has the knee flexion the spec asked for.

    Read back through the real `mean_knee_flexion_deg()` (X1) on the RAW frames, so a
    bug in `_leg_points()`'s trigonometry fails loudly here instead of silently
    producing a corpus whose specs describe a movement it does not contain. Raw, not
    preprocessed: One Euro legitimately shifts the peak (see `_make_world`), so
    asserting on the smoothed signal would be asserting on the filter, not the geometry.
    """
    raw_peak = max(mean_knee_flexion_deg(frame) for frame in frames)
    # Tolerance covers only POSE_NOISE_M's effect on the angle; the profile itself
    # reaches the requested peak exactly.
    if abs(raw_peak - spec["peak_flexion_deg"]) > 1.0:
        raise AssertionError(
            f"{spec['sample_id']}: constructed pose peaks at {raw_peak:.2f} deg but the "
            f"spec asked for {spec['peak_flexion_deg']:.2f} deg — _leg_points() is not "
            "reproducing the requested angle."
        )


def build_corpus() -> list[dict]:
    rng = random.Random(SEED)
    manifest = []
    for spec in SAMPLE_SPECS:
        frames = _build_frames(spec, rng)
        _verify_construction(spec, frames)
        measured = analyse(frames)
        (CORPUS_DIR / f"{spec['sample_id']}.json").write_text(
            json.dumps(frames, separators=(",", ":"))
        )
        manifest.append(
            {
                "sample_id": spec["sample_id"],
                "frames_file": f"{spec['sample_id']}.json",
                "n_frames": len(frames),
                "target_band_hint": spec["target_band_hint"],
                # The band the real pipeline actually produced, measured at build
                # time. This is the field the tests assert against.
                "measured": measured,
                "hint_matched": measured["band"] == spec["target_band_hint"],
                "spec": {
                    key: spec[key]
                    for key in sorted(spec)
                    if key not in {"sample_id", "target_band_hint"}
                },
            }
        )
    return manifest


def main() -> None:
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    manifest = build_corpus()
    model_version = get_model_bundle("squat").model_version
    (CORPUS_DIR / "labels.json").write_text(
        json.dumps(
            {
                "generator": "ml/scripts/generate_squat_replay_corpus.py",
                "seed": SEED,
                "fps": FPS,
                "model": model_version,
                "config_at_build": {
                    key: MODULE_B_CORE_CONFIG[key]
                    for key in (
                        "w_rule_default",
                        "w_ml_default",
                        "confidence_low_threshold",
                        "q_min",
                        "feature_schema_version",
                    )
                },
                "note": (
                    "`measured` is what the real pipeline produced at build time, not "
                    "a hand-written expectation. Stage 5.8 swapped in the trained "
                    "model (`model_version` above): unlike the Phase 4 StubModel "
                    "placeholder, there is no closed-form rule mapping a rule_score to "
                    "a reachable band any more — the forest's decision boundary and its "
                    "calibration are learned, not analytic, so which band a given "
                    "synthetic sample lands in can only be discovered by running it "
                    "through the real pipeline, which is what this manifest records. "
                    "Regenerate this file after any retraining rather than editing it."
                ),
                "samples": manifest,
            },
            indent=2,
        )
        + "\n"
    )

    print(f"[corpus] Wrote {len(manifest)} samples + labels.json to {CORPUS_DIR}")
    for item in manifest:
        measured = item["measured"]
        flag = "OK " if item["hint_matched"] else "!! "
        print(
            f"  {flag}{item['sample_id']:28s} band={str(measured['band']):5s} "
            f"(hint {item['target_band_hint']:5s}) reps={measured['n_reps']} "
            f"rule={measured.get('rule_score')} q={measured.get('q')} "
            f"peak={measured.get('peak_knee_flexion_deg')}deg "
            f"flags={measured.get('flags')}"
        )
    mismatched = [item["sample_id"] for item in manifest if not item["hint_matched"]]
    if mismatched:
        print(f"\n[corpus] NOTE: measured band != hint for: {', '.join(mismatched)}")
        print(
            "[corpus] The manifest records the measured band; fix the spec or the hint."
        )


if __name__ == "__main__":
    main()
